### ISSUE TITLE
Unhandled exception (Index was out of range) on some tags in dataset

### ISSUE THREAD

**Issue by Darkenlord1** [starik222/BooruDatasetTagManager#98]
When there are tags like those in one file (all together):
> abigail williams (fate), abigail williams (swimsuit foreigner) (fate), abigail williams (swimsuit foreigner) (third ascension) (fate)

When getting rid of all except one - works fine.

Getting this error:
![image](https://github.com/starik222/BooruDatasetTagManager/assets/20936024/cb8692c4-7601-4daa-a200-503f9972a833)
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)
   at BooruDatasetTagManager.EditableTagList.DeduplicateTags() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 229
   at BooruDatasetTagManager.EditableTagList.ToString() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 89
   at System.String.JoinCore(ReadOnlySpan`1 separator, Object[] values)
   at BooruDatasetTagManager.DatasetManager.DataItem.ToString() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 420
   at BooruDatasetTagManager.DatasetManager.DataItem.GetHashCode() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 425
   at BooruDatasetTagManager.DatasetManager.DataItem.GetTagsFromFile() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 416
   at BooruDatasetTagManager.DatasetManager.DataItem.LoadData(String imagePath, Int32 imageSize) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 382
   at BooruDatasetTagManager.DatasetManager.<>c__DisplayClass24_0.<LoadFromFolder>b__2(String x) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 254
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at BooruDatasetTagManager.DatasetManager.LoadFromFolder(String folder) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 0
   at BooruDatasetTagManager.MainForm.openFolderToolStripMenuItem_Click(Object sender, EventArgs e) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 121
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Comment by Xiahussheng** [comment]
I'm having the same problem.

**Comment by starik222** [comment]
Fixed in [2.0.2](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.2)

**Comment by rzfw** [comment]
Hi,

Still getting this issue

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.InvalidAsynchronousStateException: List desynchronization detected!
   at BooruDatasetTagManager.EditableTagList.OnListChanged(ListChangedEventArgs ev) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 551
   at BooruDatasetTagManager.EditableTagList.OnInsertComplete(Int32 index, Object value) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 581
   at System.Collections.CollectionBase.System.Collections.IList.Insert(Int32 index, Object value)
   at BooruDatasetTagManager.EditableTagList.InsertNew(Int32 index) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 437
   at BooruDatasetTagManager.MainForm.AddNewRow() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 358
   at BooruDatasetTagManager.MainForm.BtnAddTag_Clicked(Object sender, EventArgs e) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 319
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    Assembly Version: 2.0.2.0
    Win32 Version: 2.0.2.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
BooruDatasetTagManager.resources
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/en-US/BooruDatasetTagManager.resources.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
TabControl
    Assembly Version: 2.1.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/TabControl.dll
----------------------------------------
PagedControl
    Assembly Version: 2.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/PagedControl.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
Grpc.Net.Client
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Grpc.Net.Client.dll
----------------------------------------
Grpc.Core.Api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Grpc.Core.Api.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/netstandard.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Grpc.Net.Common
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/Grpc.Net.Common.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.IO.Compression.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Core.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.Process.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Net.NameResolution.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Text.RegularExpressions.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///D:/AI%20Stuff/Tag%20Manager/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************


`
